interface CountryTranslation {
    zh: string;
    "zh-hk": string;
}

interface CountriesData {
    [country: string]: CountryTranslation;
}

export const countries: CountriesData = {
    "Afghanistan": { zh: "阿富汗", "zh-hk": "阿富汗" },
    "Albania": { zh: "阿尔巴尼亚", "zh-hk": "阿爾巴尼亞" },
    "Algeria": { zh: "阿尔及利亚", "zh-hk": "阿爾及利亞" },
    "Andorra": { zh: "安道尔", "zh-hk": "安道爾" },
    "Angola": { zh: "安哥拉", "zh-hk": "安哥拉" },
    "Antigua and Barbuda": { zh: "安提瓜和巴布达", "zh-hk": "安提瓜和巴布達" },
    "Argentina": { zh: "阿根廷", "zh-hk": "阿根廷" },
    "Armenia": { zh: "亚美尼亚", "zh-hk": "亞美尼亞" },
    "Australia": { zh: "澳大利亚", "zh-hk": "澳大利亞" },
    "Austria": { zh: "奥地利", "zh-hk": "奧地利" },
    "Azerbaijan": { zh: "阿塞拜疆", "zh-hk": "阿塞拜疆" },
    "Bahamas": { zh: "巴哈马", "zh-hk": "巴哈馬" },
    "Bahrain": { zh: "巴林", "zh-hk": "巴林" },
    "Bangladesh": { zh: "孟加拉国", "zh-hk": "孟加拉國" },
    "Barbados": { zh: "巴巴多斯", "zh-hk": "巴巴多斯" },
    "Belarus": { zh: "白俄罗斯", "zh-hk": "白俄羅斯" },
    "Belgium": { zh: "比利时", "zh-hk": "比利時" },
    "Belize": { zh: "伯利兹", "zh-hk": "伯利茲" },
    "Benin": { zh: "贝宁", "zh-hk": "貝寧" },
    "Bhutan": { zh: "不丹", "zh-hk": "不丹" },
    "Bolivia": { zh: "玻利维亚", "zh-hk": "玻利維亞" },
    "Bosnia and Herzegovina": { zh: "波斯尼亚和黑塞哥维那", "zh-hk": "波斯尼亞和黑塞哥維那" },
    "Botswana": { zh: "博茨瓦纳", "zh-hk": "博茨瓦納" },
    "Brazil": { zh: "巴西", "zh-hk": "巴西" },
    "Brunei": { zh: "文莱", "zh-hk": "文萊" },
    "Bulgaria": { zh: "保加利亚", "zh-hk": "保加利亞" },
    "Burkina Faso": { zh: "布基纳法索", "zh-hk": "布基納法索" },
    "Burundi": { zh: "布隆迪", "zh-hk": "布隆迪" },
    "Cabo Verde": { zh: "佛得角", "zh-hk": "佛得角" },
    "Cambodia": { zh: "柬埔寨", "zh-hk": "柬埔寨" },
    "Cameroon": { zh: "喀麦隆", "zh-hk": "喀麥隆" },
    "Canada": { zh: "加拿大", "zh-hk": "加拿大" },
    "Central African Republic": { zh: "中非共和国", "zh-hk": "中非共和國" },
    "Chad": { zh: "乍得", "zh-hk": "乍得" },
    "Chile": { zh: "智利", "zh-hk": "智利" },
    "China": { zh: "中国", "zh-hk": "中國" },
    "Colombia": { zh: "哥伦比亚", "zh-hk": "哥倫比亞" },
    "Comoros": { zh: "科摩罗", "zh-hk": "科摩羅" },
    "Congo (Congo-Brazzaville)": { zh: "刚果（布拉柴维尔）", "zh-hk": "剛果（布拉柴維爾）" },
    "Congo (Democratic Republic of the)": { zh: "刚果民主共和国", "zh-hk": "剛果民主共和國" },
    "Costa Rica": { zh: "哥斯达黎加", "zh-hk": "哥斯達黎加" },
    "Croatia": { zh: "克罗地亚", "zh-hk": "克羅地亞" },
    "Cuba": { zh: "古巴", "zh-hk": "古巴" },
    "Cyprus": { zh: "塞浦路斯", "zh-hk": "塞浦路斯" },
    "Czechia (Czech Republic)": { zh: "捷克", "zh-hk": "捷克" },
    "Denmark": { zh: "丹麦", "zh-hk": "丹麥" },
    "Djibouti": { zh: "吉布提", "zh-hk": "吉布提" },
    "Dominica": { zh: "多米尼克", "zh-hk": "多米尼克" },
    "Dominican Republic": { zh: "多米尼加共和国", "zh-hk": "多米尼加共和國" },
    "Ecuador": { zh: "厄瓜多尔", "zh-hk": "厄瓜多爾" },
    "Egypt": { zh: "埃及", "zh-hk": "埃及" },
    "El Salvador": { zh: "萨尔瓦多", "zh-hk": "薩爾瓦多" },
    "Equatorial Guinea": { zh: "赤道几内亚", "zh-hk": "赤道幾內亞" },
    "Eritrea": { zh: "厄立特里亚", "zh-hk": "厄立特里亞" },
    "Estonia": { zh: "爱沙尼亚", "zh-hk": "愛沙尼亞" },
    "Eswatini (Swaziland)": { zh: "斯威士兰", "zh-hk": "斯威士蘭" },
    "Ethiopia": { zh: "埃塞俄比亚", "zh-hk": "埃塞俄比亞" },
    "Fiji": { zh: "斐济", "zh-hk": "斐濟" },
    "Finland": { zh: "芬兰", "zh-hk": "芬蘭" },
    "France": { zh: "法国", "zh-hk": "法國" },
    "Gabon": { zh: "加蓬", "zh-hk": "加蓬" },
    "Gambia": { zh: "冈比亚", "zh-hk": "岡比亞" },
    "Georgia": { zh: "格鲁吉亚", "zh-hk": "格魯吉亞" },
    "Germany": { zh: "德国", "zh-hk": "德國" },
    "Ghana": { zh: "加纳", "zh-hk": "加納" },
    "Greece": { zh: "希腊", "zh-hk": "希臘" },
    "Grenada": { zh: "格林纳达", "zh-hk": "格林納達" },
    "Guatemala": { zh: "危地马拉", "zh-hk": "危地馬拉" },
    "Guinea": { zh: "几内亚", "zh-hk": "幾內亞" },
    "Guinea-Bissau": { zh: "几内亚比绍", "zh-hk": "幾內亞比紹" },
    "Guyana": { zh: "圭亚那", "zh-hk": "圭亞那" },
    "Haiti": { zh: "海地", "zh-hk": "海地" },
    "Honduras": { zh: "洪都拉斯", "zh-hk": "洪都拉斯" },
    "Hong Kong": { zh: "香港", "zh-hk": "香港" },
    "Hungary": { zh: "匈牙利", "zh-hk": "匈牙利" },
    "Iceland": { zh: "冰岛", "zh-hk": "冰島" },
    "India": { zh: "印度", "zh-hk": "印度" },
    "Indonesia": { zh: "印度尼西亚", "zh-hk": "印度尼西亞" },
    "Iran": { zh: "伊朗", "zh-hk": "伊朗" },
    "Iraq": { zh: "伊拉克", "zh-hk": "伊拉克" },
    "Ireland": { zh: "爱尔兰", "zh-hk": "愛爾蘭" },
    "Israel": { zh: "以色列", "zh-hk": "以色列" },
    "Italy": { zh: "意大利", "zh-hk": "意大利" },
    "Jamaica": { zh: "牙买加", "zh-hk": "牙買加" },
    "Japan": { zh: "日本", "zh-hk": "日本" },
    "Jordan": { zh: "约旦", "zh-hk": "約旦" },
    "Kazakhstan": { zh: "哈萨克斯坦", "zh-hk": "哈薩克斯坦" },
    "Kenya": { zh: "肯尼亚", "zh-hk": "肯尼亞" },
    "Kiribati": { zh: "基里巴斯", "zh-hk": "基里巴斯" },
    "Korea (North)": { zh: "朝鲜", "zh-hk": "朝鮮" },
    "Korea (South)": { zh: "韩国", "zh-hk": "韓國" },
    "Kuwait": { zh: "科威特", "zh-hk": "科威特" },
    "Kyrgyzstan": { zh: "吉尔吉斯斯坦", "zh-hk": "吉爾吉斯斯坦" },
    "Laos": { zh: "老挝", "zh-hk": "老撾" },
    "Latvia": { zh: "拉脱维亚", "zh-hk": "拉脫維亞" },
    "Lebanon": { zh: "黎巴嫩", "zh-hk": "黎巴嫩" },
    "Lesotho": { zh: "莱索托", "zh-hk": "萊索托" },
    "Liberia": { zh: "利比里亚", "zh-hk": "利比里亞" },
    "Libya": { zh: "利比亚", "zh-hk": "利比亞" },
    "Liechtenstein": { zh: "列支敦士登", "zh-hk": "列支敦士登" },
    "Lithuania": { zh: "立陶宛", "zh-hk": "立陶宛" },
    "Luxembourg": { zh: "卢森堡", "zh-hk": "盧森堡" },
    "Madagascar": { zh: "马达加斯加", "zh-hk": "馬達加斯加" },
    "Malawi": { zh: "马拉维", "zh-hk": "馬拉維" },
    "Malaysia": { zh: "马来西亚", "zh-hk": "馬來西亞" },
    "Maldives": { zh: "马尔代夫", "zh-hk": "馬爾代夫" },
    "Mali": { zh: "马里", "zh-hk": "馬里" },
    "Malta": { zh: "马耳他", "zh-hk": "馬耳他" },
    "Marshall Islands": { zh: "马绍尔群岛", "zh-hk": "馬紹爾群島" },
    "Mauritania": { zh: "毛里塔尼亚", "zh-hk": "毛里塔尼亞" },
    "Mauritius": { zh: "毛里求斯", "zh-hk": "毛里求斯" },
    "Mexico": { zh: "墨西哥", "zh-hk": "墨西哥" },
    "Micronesia": { zh: "密克罗尼西亚", "zh-hk": "密克羅尼西亞" },
    "Moldova": { zh: "摩尔多瓦", "zh-hk": "摩爾多瓦" },
    "Monaco": { zh: "摩纳哥", "zh-hk": "摩納哥" },
    "Mongolia": { zh: "蒙古", "zh-hk": "蒙古" },
    "Montenegro": { zh: "黑山", "zh-hk": "黑山" },
    "Morocco": { zh: "摩洛哥", "zh-hk": "摩洛哥" },
    "Mozambique": { zh: "莫桑比克", "zh-hk": "莫桑比克" },
    "Myanmar (Burma)": { zh: "缅甸", "zh-hk": "緬甸" },
    "Namibia": { zh: "纳米比亚", "zh-hk": "納米比亞" },
    "Nauru": { zh: "瑙鲁", "zh-hk": "瑙魯" },
    "Nepal": { zh: "尼泊尔", "zh-hk": "尼泊爾" },
    "Netherlands": { zh: "荷兰", "zh-hk": "荷蘭" },
    "New Zealand": { zh: "新西兰", "zh-hk": "新西蘭" },
    "Nicaragua": { zh: "尼加拉瓜", "zh-hk": "尼加拉瓜" },
    "Niger": { zh: "尼日尔", "zh-hk": "尼日爾" },
    "Nigeria": { zh: "尼日利亚", "zh-hk": "尼日利亞" },
    "North Macedonia (Macedonia)": { zh: "北马其顿", "zh-hk": "北馬其頓" },
    "Norway": { zh: "挪威", "zh-hk": "挪威" },
    "Oman": { zh: "阿曼", "zh-hk": "阿曼" },
    "Pakistan": { zh: "巴基斯坦", "zh-hk": "巴基斯坦" },
    "Palau": { zh: "帕劳", "zh-hk": "帕勞" },
    "Palestine State": { zh: "巴勒斯坦", "zh-hk": "巴勒斯坦" },
    "Panama": { zh: "巴拿马", "zh-hk": "巴拿馬" },
    "Papua New Guinea": { zh: "巴布亚新几内亚", "zh-hk": "巴布亞新幾內亞" },
    "Paraguay": { zh: "巴拉圭", "zh-hk": "巴拉圭" },
    "Peru": { zh: "秘鲁", "zh-hk": "秘魯" },
    "Philippines": { zh: "菲律宾", "zh-hk": "菲律賓" },
    "Poland": { zh: "波兰", "zh-hk": "波蘭" },
    "Portugal": { zh: "葡萄牙", "zh-hk": "葡萄牙" },
    "Qatar": { zh: "卡塔尔", "zh-hk": "卡塔爾" },
    "Romania": { zh: "罗马尼亚", "zh-hk": "羅馬尼亞" },
    "Russia": { zh: "俄罗斯", "zh-hk": "俄羅斯" },
    "Rwanda": { zh: "卢旺达", "zh-hk": "盧旺達" },
    "Saint Kitts and Nevis": { zh: "圣基茨和尼维斯", "zh-hk": "聖基茨和尼維斯" },
    "Saint Lucia": { zh: "圣卢西亚", "zh-hk": "聖盧西亞" },
    "Saint Vincent and the Grenadines": { zh: "圣文森特和格林纳丁斯", "zh-hk": "聖文森特和格林納丁斯" },
    "Samoa": { zh: "萨摩亚", "zh-hk": "薩摩亞" },
    "San Marino": { zh: "圣马力诺", "zh-hk": "聖馬力諾" },
    "Sao Tome and Principe": { zh: "圣多美和普林西比", "zh-hk": "聖多美和普林西比" },
    "Saudi Arabia": { zh: "沙特阿拉伯", "zh-hk": "沙特阿拉伯" },
    "Senegal": { zh: "塞内加尔", "zh-hk": "塞內加爾" },
    "Serbia": { zh: "塞尔维亚", "zh-hk": "塞爾維亞" },
    "Seychelles": { zh: "塞舌尔", "zh-hk": "塞舌爾" },
    "Sierra Leone": { zh: "塞拉利昂", "zh-hk": "塞拉利昂" },
    "Singapore": { zh: "新加坡", "zh-hk": "新加坡" },
    "Slovakia": { zh: "斯洛伐克", "zh-hk": "斯洛伐克" },
    "Slovenia": { zh: "斯洛文尼亚", "zh-hk": "斯洛文尼亞" },
    "Solomon Islands": { zh: "所罗门群岛", "zh-hk": "所羅門群島" },
    "Somalia": { zh: "索马里", "zh-hk": "索馬里" },
    "South Africa": { zh: "南非", "zh-hk": "南非" },
    "South Sudan": { zh: "南苏丹", "zh-hk": "南蘇丹" },
    "Spain": { zh: "西班牙", "zh-hk": "西班牙" },
    "Sri Lanka": { zh: "斯里兰卡", "zh-hk": "斯里蘭卡" },
    "Sudan": { zh: "苏丹", "zh-hk": "蘇丹" },
    "Suriname": { zh: "苏里南", "zh-hk": "蘇里南" },
    "Sweden": { zh: "瑞典", "zh-hk": "瑞典" },
    "Switzerland": { zh: "瑞士", "zh-hk": "瑞士" },
    "Syria": { zh: "叙利亚", "zh-hk": "敘利亞" },
    "Tajikistan": { zh: "塔吉克斯坦", "zh-hk": "塔吉克斯坦" },
    "Taiwan": { zh: "台湾", "zh-hk": "台灣" },
    "Tanzania": { zh: "坦桑尼亚", "zh-hk": "坦桑尼亞" },
    "Thailand": { zh: "泰国", "zh-hk": "泰國" },
    "Timor-Leste": { zh: "东帝汶", "zh-hk": "東帝汶" },
    "Togo": { zh: "多哥", "zh-hk": "多哥" },
    "Tonga": { zh: "汤加", "zh-hk": "湯加" },
    "Trinidad and Tobago": { zh: "特立尼达和多巴哥", "zh-hk": "特立尼達和多巴哥" },
    "Tunisia": { zh: "突尼斯", "zh-hk": "突尼斯" },
    "Turkey": { zh: "土耳其", "zh-hk": "土耳其" },
    "Turkmenistan": { zh: "土库曼斯坦", "zh-hk": "土庫曼斯坦" },
    "Tuvalu": { zh: "图瓦卢", "zh-hk": "圖瓦盧" },
    "Uganda": { zh: "乌干达", "zh-hk": "烏干達" },
    "Ukraine": { zh: "乌克兰", "zh-hk": "烏克蘭" },
    "United Arab Emirates": { zh: "阿拉伯联合酋长国", "zh-hk": "阿拉伯聯合酋長國" },
    "United Kingdom": { zh: "英国", "zh-hk": "英國" },
    "United States of America": { zh: "美国", "zh-hk": "美國" },
    "Uruguay": { zh: "乌拉圭", "zh-hk": "烏拉圭" },
    "Uzbekistan": { zh: "乌兹别克斯坦", "zh-hk": "烏茲別克斯坦" },
    "Vanuatu": { zh: "瓦努阿图", "zh-hk": "瓦努阿圖" },
    "Vatican City (Holy See)": { zh: "梵蒂冈", "zh-hk": "梵蒂岡" },
    "Venezuela": { zh: "委内瑞拉", "zh-hk": "委內瑞拉" },
    "Vietnam": { zh: "越南", "zh-hk": "越南" },
    "Yemen": { zh: "也门", "zh-hk": "也門" },
    "Zambia": { zh: "赞比亚", "zh-hk": "贊比亞" },
    "Zimbabwe": { zh: "津巴布韦", "zh-hk": "津巴布韋" }
};
